-   id: tsc
    name: tsc
    description: 'Compile TypeScript.'
    entry: tsc
    language: node
    types_or: [ts, tsx]
    pass_filenames: false
    args: [--noEmit]
    additional_dependencies: ["typescript@5.9"]
    minimum_pre_commit_version: '0'
